#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Utils
import os
 
def options(opt):
	# stub
	return

def configure(conf):
	# stub
	return

def build(bld):
	source = bld.path.parent.ant_glob([
		'pm_shared/*.c'
	])
	
	source += [
		'cdll_int.cpp', '../game_shared/common.cpp', 'entity.cpp', 'hud.cpp',
		'hud_draw.cpp', 'hud_msg.cpp', 'hud_redraw.cpp', 'hud_sbar.cpp',
		'hud_update.cpp', 'in_camera.cpp', 'input.cpp', 'input_xash3d.cpp', 'input_mouse.cpp',
		'message.cpp', 'parsemsg.cpp', 'saytext.cpp', 'scoreboard.cpp',
		'../game_shared/stringlib.cpp', 'StudioModelRenderer.cpp', 'text_message.cpp',
		'util.cpp', 'view.cpp'
	]

	includes = Utils.to_list('. ../common ../engine ../game_shared ../dlls ../pm_shared ')

	libs = []

	defines = ['CLIENT_DLL']

	if bld.env.DEST_OS2 not in ['android']:
		install_path = os.path.join(bld.env.GAMEDIR, bld.env.CLIENT_DIR)
	else:
		install_path = bld.env.PREFIX

	bld.shlib(
		source   = source,
		target   = 'client',
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = 1
	)
