#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Utils
import os
 
def options(opt):
	# stub
	return

def configure(conf):
	# stub
	return

def build(bld):
	defines = []
	source = bld.path.parent.ant_glob([
		'pm_shared/*.c',
	])
	
	source += [
		'client.cpp', '../game_shared/common.cpp', 'crc.cpp', 'dll_int.cpp', 'game.cpp', 'globals.cpp', 'physics.cpp', 
		'pr_cmds.cpp', 'pr_edict.cpp', 'pr_exec.cpp', 'pr_message.cpp', 'pr_move.cpp', 
		'pr_phys.cpp', 'pr_save.cpp', 'pr_world.cpp', 'saverestore.cpp', 
		'../game_shared/stringlib.cpp', 'util.cpp']

	includes = Utils.to_list('. ../common ../engine ../pm_shared ../game_shared')

	libs = []

	if bld.env.DEST_OS2 not in ['android']:
		install_path = os.path.join(bld.env.GAMEDIR, bld.env.SERVER_DIR)
	else:
		install_path = bld.env.PREFIX

	bld.shlib(
		source   = source,
		target   = 'server',
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = 2
	)
